---
driver:
  name: vagrant
  require_chef_omnibus: 11.18.12

driver_config:
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  attributes:
    apt:
      compile_time_update: true
    java:
      install_flavor: oracle
      java_home: /usr/lib/jvm/java-7-oracle
      jdk_version: 7
      oracle:
        accept_oracle_download_terms: true

platforms:

- name: centos-6
  driver_config:
    box: chef/centos-6.6  # vagrant
    image: centos-6-5-x64 # digitalocean
  run_list:
  - recipe[yum]

- name: centos-7
  driver_config:
    box: chef/centos-7.0
    image: centos-7-0-x64
  run_list:
  - recipe[yum]

- name: ubuntu-12.04
  driver_config:
    box: chef/ubuntu-12.04
    image: ubuntu-12-04-x64
  run_list:
  - recipe[apt]

- name: ubuntu-14.04
  driver_config:
    box: chef/ubuntu-14.04
    image: ubuntu-14-04-x64
  run_list:
  - recipe[apt]

suites:
- name: mysql # default
  run_list:
  - recipe[test-helper]
  - recipe[java]
  - recipe[stash]
  attributes:
    stash:
      database:
        password: iloverandompasswordsbutthiswilldo

- name: postgresql
  run_list:
  - recipe[test-helper]
  - recipe[java]
  - recipe[stash]
  attributes:
    stash:
      database:
        type: postgresql
    postgresql:
      password:
        postgres: iloverandompasswordsbutthiswilldo
