driver:
  name: digitalocean
  private_networking: false
  size: 1gb

provisioner:
  client_rb:
    formatters:
      # Travis CI will cancel job if logs get over 4MB.
    - :minimal
  attributes:
    stash:
      jvm:
        maximum_memory: 1024m

platforms:

- name: centos-6
  driver_config:
    image: centos-6-5-x64
  run_list:
  - recipe[yum]

- name: centos-7
  driver_config:
    image: centos-7-0-x64
  run_list:
  - recipe[yum]

- name: ubuntu-12.04
  driver_config:
    image: ubuntu-12-04-x64
  run_list:
  - recipe[apt]

- name: ubuntu-14.04
  driver_config:
    image: ubuntu-14-04-x64
  run_list:
  - recipe[apt]
