---
driver:
  name: vagrant
  require_chef_omnibus: 11.16.2
  network:
    - ["private_network", {ip: "192.168.50.10"}]

driver_config:
  customize:
    memory: 1024

platforms:
- name: centos-6.7
  driver_config:
    box: bento/centos-6.7
  run_list:
  - recipe[yum]
- name: centos-7.1
  driver_config:
    box: bento/centos-7.1
  run_list:
  - recipe[yum]
- name: ubuntu-12.04
  driver_config:
    box: bento/ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  driver_config:
    box: bento/ubuntu-14.04
  run_list:
  - recipe[apt]

default_attributes: &DEFAULT_ATTRIBUTES
  java:
    install_flavor: oracle
    java_home: /usr/lib/jvm/java-8-oracle
    jdk_version: 8
    oracle:
      accept_oracle_download_terms: true

suites:
- name: mysql # default
  run_list:
  - recipe[test-helper]
  - recipe[java]
  - recipe[stash]
  attributes:
    <<: *DEFAULT_ATTRIBUTES
    stash:
      database:
        type: mysql
    mysql:
      server_root_password: iloverandompasswordsbutthiswilldo
      server_repl_password: iloverandompasswordsbutthiswilldo
      server_debian_password: iloverandompasswordsbutthiswilldo

- name: postgresql
  run_list:
  - recipe[test-helper]
  - recipe[java]
  - recipe[stash]
  attributes:
    <<: *DEFAULT_ATTRIBUTES
    postgresql:
      password:
        postgres: iloverandompasswordsbutthiswilldo
