---
driver:
  name: vagrant
  require_chef_omnibus: 11.16.2

driver_config:
  customize:
    memory: 1024

provisioner:
  name: chef_zero

platforms:
- name: centos-6
  driver_config:
    box: chef/centos-6.6
  run_list:
  - recipe[yum]
- name: centos-7
  driver_config:
    box: chef/centos-7.0
  run_list:
  - recipe[yum]
- name: ubuntu-12.04
  driver_config:
    box: chef/ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  driver_config:
    box: chef/ubuntu-14.04
  run_list:
  - recipe[apt]

default_attributes: &DEFAULT_ATTRIBUTES
  apt:
    compile_time_update: true
  java:
    install_flavor: oracle
    java_home: /usr/lib/jvm/java-7-oracle
    jdk_version: 7
    oracle:
      accept_oracle_download_terms: true

suites:
- name: mysql # default
  run_list:
  - recipe[test-helper]
  - recipe[java]
  - recipe[stash]
  attributes:
    <<: *DEFAULT_ATTRIBUTES
    stash:
      database:
        password: iloverandompasswordsbutthiswilldo
- name: postgresql
  run_list:
  - recipe[test-helper]
  - recipe[java]
  - recipe[stash]
  attributes:
    <<: *DEFAULT_ATTRIBUTES
    stash:
      database:
        type: postgresql
    postgresql:
      password:
        postgres: iloverandompasswordsbutthiswilldo
