driver:
  name: digitalocean
  private_networking: false
  size: 1gb

provisioner:
  client_rb:
    formatters:
      # Travis CI will cancel job if logs get over 4MB.
    - :minimal
  attributes:
    stash:
      jvm:
        maximum_memory: 1024m
