driver:
  name: digitalocean
  private_networking: false
  size: 1024mb

cloud_attributes: &CLOUD_ATTRIBUTES
  stash:
    jvm:
      maximum_memory: 1024m

platforms:
- name: centos-6
  attributes: *CLOUD_ATTRIBUTES
  driver_config:
    image: centos-6-5-x64
- name: centos-7
  driver_config:
    image: centos-7-0-x64
- name: ubuntu-12.04
  driver_config:
    image: ubuntu-12-04-x64
- name: ubuntu-14.04
  driver_config:
    image: ubuntu-14-04-x64
