AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Guardfile
    - Rakefile
  Exclude:
    - test/**/*
    - spec/**/*
    - vendor/**/*
    - ruby/**/*
    - Vagrantfile
  TargetRubyVersion: 2.4

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
  Exclude:
    - "libraries/helper.rb"
Style/NumericLiteralPrefix:
  Enabled: false
Metrics/ModuleLength:
  Exclude:
    - "libraries/helper.rb"
Metrics/AbcSize:
  Exclude:
    - "libraries/helper.rb"
Metrics/CyclomaticComplexity:
  Exclude:
    - "libraries/helper.rb"
Metrics/PerceivedComplexity:
  Exclude:
    - "libraries/helper.rb"
